version: 2
build:
  os: ubuntu-24.04
  tools:
    python: '3.14'
  jobs:
    install:
      - pip install --upgrade pip
      - pip install --group 'docs' .
    build:
      html:
        - make docs
    post_build:
      - mkdir -p $READTHEDOCS_OUTPUT/html/
      - cp --recursive docs/site/* $READTHEDOCS_OUTPUT/html/
